### ISSUE TITLE
nan in output files

### ISSUE THREAD

**Issue by jxlabWzZ** [makovalab-psu/AmpliCoNE-tool#3]
Hi, 
I used your pipelines to build a custom annotation file, and found nan in the CNV output, Why did this happen?

Ampliconic_Summary.txt
GeneFamily      CopyNumber(MAP=1)       CopyNumber(XDG)
HSFY    nan     nan
TSPY3   2.25752325783   nan

XDG_CopyNumber.txt
Gene    CopyNumber
CONTROL_31222464_31300800       1.14085815055
CONTROL_30902624_30953126       nan
CONTROL_19915884_19968160       0.848001937654
CONTROL_20971328_21022705       1.01405630461
CONTROL_19540825_19591120       0.973605811139
CONTROL_20859472_20916608       1.18062767662
CONTROL_21997005_22063205       0.0
CONTROL_19174889_19233744       0.893719731718
CONTROL_19292592_19373856       0.930941933957

**Comment by rahulsimham** [comment]
The most likely reason is there are no sites in one of your control regions
with mappability value 1. Try removing the control gene with nan values and
run AmpliCoNE. It's hard to debug with out looking at the data.

Rahul

**Comment by jxlabWzZ** [comment]
Your understanding may be right, and we apply the modified version: https://github.com/ekopania/modified-AmpliCoNE, the result is normal. 

However, we found that the CN consistency between father and son is not so good :
（father.HSFY~=69 son.HSFY~=75）
（father.TSPY~=2.2 son.TSPY~=2.3）

Therefore , how can we improve the accuracy? 

Its a custom genome, and our genome and data are not yet published.

**Comment by rahulsimham** [comment]
Are these biological samples or simulated data.  If they are biological
samples then you could expect differences in copy number between father and
son. Sorry for the delayed response.

Rahul
