### ISSUE TITLE
Representative Sequences for gene definition in multiple species?

### ISSUE THREAD

**Issue by aabiddanda** [makovalab-psu/AmpliCoNE-tool#4]
I am currently trying to generate a gene definition file for multiple primates using the sequences  from the hg38 gene definition provided with `AmpliCONE`. 

One thing that is unclear to me is the "Representative Gene" statement below. Did you use any specific rules for defining these representative genes in hg38? My current definition is to choose the most "complete" (e.g. fewest N and lowercase) sequence out of the copies but seem to be getting many more rows when running `blat` per representative sequence than should be possible. 

Any notes or tips on this would be helpful! 

```
Step2: Generate gene definition file
Format : TSV
Columns : Start Position, End Position and Gene Family Name
Rows : Gene copy
NOTE: For gene copies in control, the gene family name (3rd column) should be "CONTROL".(case sensitive)

How to generate the file:

Identify a representative gene for each gene family and extract its sequence from NCBI.
BLAT the representative gene sequence against reference genome to identify all locations with greater than 99% identity.
Represent each location identified with its start and end location followed by the gene family name.
```

**Comment by karolpal-jr** [comment]
Hi Arjun, I've added some info into the documentation about the representative sequence.
